// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: bootstrap.proto

package protofiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JoinInfoRequest contains information about a node in the network
type JoinInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address where the node can be reached
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinInfoRequest) Reset() {
	*x = JoinInfoRequest{}
	mi := &file_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinInfoRequest) ProtoMessage() {}

func (x *JoinInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinInfoRequest.ProtoReflect.Descriptor instead.
func (*JoinInfoRequest) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *JoinInfoRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// JoinInfoResponse contains a list of active nodes in the network
type JoinInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimensions    uint32                 `protobuf:"varint,1,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	NumHashes     uint32                 `protobuf:"varint,2,opt,name=num_hashes,json=numHashes,proto3" json:"num_hashes,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActiveNodes   []string               `protobuf:"bytes,4,rep,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"` // IP Addresses of active nodes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinInfoResponse) Reset() {
	*x = JoinInfoResponse{}
	mi := &file_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinInfoResponse) ProtoMessage() {}

func (x *JoinInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinInfoResponse.ProtoReflect.Descriptor instead.
func (*JoinInfoResponse) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *JoinInfoResponse) GetDimensions() uint32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *JoinInfoResponse) GetNumHashes() uint32 {
	if x != nil {
		return x.NumHashes
	}
	return 0
}

func (x *JoinInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinInfoResponse) GetActiveNodes() []string {
	if x != nil {
		return x.ActiveNodes
	}
	return nil
}

type BootstrapLeaveInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeAddress   string                 `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapLeaveInfo) Reset() {
	*x = BootstrapLeaveInfo{}
	mi := &file_bootstrap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapLeaveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapLeaveInfo) ProtoMessage() {}

func (x *BootstrapLeaveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapLeaveInfo.ProtoReflect.Descriptor instead.
func (*BootstrapLeaveInfo) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *BootstrapLeaveInfo) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

type BootstrapLeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapLeaveResponse) Reset() {
	*x = BootstrapLeaveResponse{}
	mi := &file_bootstrap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapLeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapLeaveResponse) ProtoMessage() {}

func (x *BootstrapLeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapLeaveResponse.ProtoReflect.Descriptor instead.
func (*BootstrapLeaveResponse) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{3}
}

var File_bootstrap_proto protoreflect.FileDescriptor

const file_bootstrap_proto_rawDesc = "" +
	"\n" +
	"\x0fbootstrap.proto\x12\x03can\"+\n" +
	"\x0fJoinInfoRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x8d\x01\n" +
	"\x10JoinInfoResponse\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x01 \x01(\rR\n" +
	"dimensions\x12\x1d\n" +
	"\n" +
	"num_hashes\x18\x02 \x01(\rR\tnumHashes\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12!\n" +
	"\factive_nodes\x18\x04 \x03(\tR\vactiveNodes\"7\n" +
	"\x12BootstrapLeaveInfo\x12!\n" +
	"\fnode_address\x18\x01 \x01(\tR\vnodeAddress\"\x18\n" +
	"\x16BootstrapLeaveResponse2\x8a\x01\n" +
	"\x10BootstrapService\x127\n" +
	"\bJoinInfo\x12\x14.can.JoinInfoRequest\x1a\x15.can.JoinInfoResponse\x12=\n" +
	"\x05Leave\x12\x17.can.BootstrapLeaveInfo\x1a\x1b.can.BootstrapLeaveResponseB\x0eZ\f./protofilesb\x06proto3"

var (
	file_bootstrap_proto_rawDescOnce sync.Once
	file_bootstrap_proto_rawDescData []byte
)

func file_bootstrap_proto_rawDescGZIP() []byte {
	file_bootstrap_proto_rawDescOnce.Do(func() {
		file_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bootstrap_proto_rawDesc), len(file_bootstrap_proto_rawDesc)))
	})
	return file_bootstrap_proto_rawDescData
}

var file_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bootstrap_proto_goTypes = []any{
	(*JoinInfoRequest)(nil),        // 0: can.JoinInfoRequest
	(*JoinInfoResponse)(nil),       // 1: can.JoinInfoResponse
	(*BootstrapLeaveInfo)(nil),     // 2: can.BootstrapLeaveInfo
	(*BootstrapLeaveResponse)(nil), // 3: can.BootstrapLeaveResponse
}
var file_bootstrap_proto_depIdxs = []int32{
	0, // 0: can.BootstrapService.JoinInfo:input_type -> can.JoinInfoRequest
	2, // 1: can.BootstrapService.Leave:input_type -> can.BootstrapLeaveInfo
	1, // 2: can.BootstrapService.JoinInfo:output_type -> can.JoinInfoResponse
	3, // 3: can.BootstrapService.Leave:output_type -> can.BootstrapLeaveResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bootstrap_proto_init() }
func file_bootstrap_proto_init() {
	if File_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bootstrap_proto_rawDesc), len(file_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bootstrap_proto_goTypes,
		DependencyIndexes: file_bootstrap_proto_depIdxs,
		MessageInfos:      file_bootstrap_proto_msgTypes,
	}.Build()
	File_bootstrap_proto = out.File
	file_bootstrap_proto_goTypes = nil
	file_bootstrap_proto_depIdxs = nil
}
